import React from "react";
import Menu from "./Menu";
import Head from "next/head";
import styles from "../styles/Layout.module.css";

const Layout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Menu />
        {children}
      </main>
    </div>
  );
};

export default Layout;
